### ISSUE TITLE
WOL starts device, but no ping and no Online status

### ISSUE THREAD

**Issue by Seexelas** [AlexGustafsson/homebridge-wol#217]
### Backstory

WOL starts my Windows computer, but I don't see the device online in Homebridge or Home on iOS.

### Issue

Hi, 

I need help to make the plugin fully operationnal, WOL starts my Windows computer, but I don't see the device online in Homebridge or Home on iOS.

Ping responds in Homebridge terminal. 

Thanks

### Environment

```Markdown
- os and os version: Ubuntu Focal Fossa (20.04.4 LTS)
- node version: v16.16.0
- homebridge version: v1.5.0
- homebridge-wol version: 5.0.2
```

### Configuration

            "name": "GAMING-PC",
            "manufacturer": "homebridge-wol",
            "model": "NetworkDevice",
            "host": "192.168.1.1",
            "pingInterval": 2,
            "pingsToChange": 5,
            "pingTimeout": 1,
            "pingCommand": "ping",
            "pingCommandTimeout": 0,
            "mac": "XXXXXXXX",
            "startCommandTimeout": 0,
            "wakeGraceTime": 45,
            "wakeCommandTimeout": 0,
            "shutdownCommand": "\"net rpc shutdown --ipaddress 192.168.1.1 --user Seexelas%XXXXXXX*\"",
            "shutdownGraceTime": 15,
            "shutdownCommandTimeout": 0,
            "logLevel": "Info",
            "returnEarly": false,
            "accessory": "NetworkDevice"

### Logs

```Markdown
When I follow these steps:
1. Make sure `logLevel` is set to `Debug` on all `NetworkDevice` accessories
2. Run `homebridge`
3. Let it run for a couple of minutes
4. Try to turn a device on or off using the plugin
5. Wait one minute
6. Repeat step 4

I get the following log:

Status went from waking up to offline

Please paste your log here
```
```


### Notes

_No response_

**Comment by AlexGustafsson** [comment]
If your PC doesn't respond to pings or if the IP address is wrong, the plugin won't be able to identify your PC as being on. Could you try to run `ping 192.168.1.1` on the server you're running on Homebridge on? Note that the IP is typically used for routers, so I'm assuming you just changed it to something else for this issue.

**Comment by Mark9264** [comment]
This is also happening to me, The waking up works but its not pinging for some reason, i'm not sure if this could be a hardware issue as i have 2 other computers that this works with. (All desktop PC's)

Any suggestions?

**Comment by strafe** [comment]
> Any suggestions?

As said above, you should make sure that Windows is not blocking the ping. Check the relevant ICMP rules in Windows Firewall are configured correctly. This functionality does work as long as your network is configured correctly.

**Comment by Mark9264** [comment]
Ahh i see, the firewall wasn't allowing pings through.

This is how i fixed it for others that have the same issue.

1. Search for **Windows Defender Firewall with Advanced Security**, and click to open it.
2. From the left pane of the resulting window, click Inbound Rules.
3. In the right pane, find the rules titled **File and Printer Sharing (Echo Request - ICMPv4-In)**. 
4. Right click the rule and enable it. (The private network profile is the only one i need to enable for my case).

Hope that helps

**Comment by strafe** [comment]
Yes, you'll only need to enable the Public/Private rule in 99% of cases, not the domain one.

For added "security", you can also add your Homebridge server's IP in the remote addresses section, under scope in the rule's properties. By default, once you enable the rule, any device on the network will be allowed to ping the machine.

**Comment by AlexGustafsson** [comment]
Thanks for the help, @strafe and for sharing the solution @Mark9264. @Seexelas does the solution work for you?

**Comment by Seexelas** [comment]
Hi,

Yes it's the windows firewall, I put it down and use my router one. 

It's working perfectly. I still don't understand how it is possible that Windows firewall can work with the computer complete shutdown :D

**Comment by Barba4life** [comment]
try this if your running PC,

https://manage.accuwebhosting.com/knowledgebase/2609/How-to-Allow-Pingor-ICMP-Echo-Request-in-Windows-Firewall.html

**Comment by AlexGustafsson** [comment]
Seems like this issue is solved. Closing. Feel free to reopen if you believe it's not solved.
